### PR TITLE
chore: define build configurations for jenkins CI

### PR DESCRIPTION
**Pull request by pavel-github**
This PR fixes failed jobs on Jenkins CI.

We don't want to use `buildPlugin.recommendedConfigurations()` because it may (will) change over time and our CI will break if the new recommended configuration is not compatible.

Following configurations are defined:
- linux, jdk8, latest jenkins version
- linux, jdk8, minimal supported jenkins version from our plugin (2.60.3)
- windows, jdk8, latest jenkins version
- windows, jdk8, minimal supported jenkins version from our plugin (2.60.3)

### CODE REVIEW

**Comment by pavel-github** [comment]
@alecharp 👋 , can you help me with Jenkins build configuration? I used different formats described in https://github.com/jenkins-infra/pipeline-library#optional-arguments, but it looks that steps and configurations are always the same.
Can you point me into the "right" direction? Thanks

**Comment by alecharp** [comment]
I'm not sure to understand why you don't want the recommended configuration. Of course, it might change in the future, but it's to keep the plugin in the same direction as the community.

I understand that there is currently one issue on the Java 11 / linux build, but it's a `spotbugs` issue, which is and should be fixed.

**Comment by pavel-github** [comment]
It's not only `spotbug` issue (sometime builds fail because of timeout or sporadically: VM terminated etc). And I see that many other Jenkins plugins use custom (actually linux, windows jdk8) jobs.
So how I can configure it? (change in Jenkinsfile seems not to work).

**Comment by alecharp** [comment]
so, any change in `Jenkinsfile` from a PR is not used unless the PR is opened by an admin of the `jenkinsci` org or an "admin" on the repository (correct me if I'm wrong @oleg-nenashev). 

Otherwise, your `Jenkinsfile` seems ok. 

The VM being terminated, where did you see that?

**Comment by pavel-github** [comment]
@alecharp, take a look on https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fsnyk-security-scanner-plugin/detail/PR-44/3/pipeline/12

If you compare [second](https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fsnyk-security-scanner-plugin/detail/PR-44/2/pipeline) and [third](https://ci.jenkins.io/blue/organizations/jenkins/Plugins%2Fsnyk-security-scanner-plugin/detail/PR-44/3/pipeline) runs for this PR you will see it that some jobs change state from `failed` to `success` and vice versa but there are no source code changes.

**Comment by pavel-github** [comment]
@alecharp, I reverted changes to original commit with custom configuration. If I understand you correctly the changes can be enabled if PR is opened by admin of our repository?

**Comment by alecharp** [comment]
what's happening is that the builds are occuring in parallel but to save time in case of one branch failing, those still building are stopped. This is what happened in the `linux-8` branch on the third build. So, why was this branch green on the second build? maybe because it finished before the build on `linux-11-2.164.1` was completed. That's all. 

If you push some code in this PR to fix 

```
[ERROR] Nullcheck of toolsSubDirectories at line 34 of value previously dereferenced in io.snyk.jenkins.CustomBuildToolPathCallable.invoke(File, VirtualChannel) [io.snyk.jenkins.CustomBuildToolPathCallable, io.snyk.jenkins.CustomBuildToolPathCallable] At CustomBuildToolPathCallable.java:[line 34]Redundant null check at CustomBuildToolPathCallable.java:[line 41] RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE
```

you might see all the builds turning green.

**Comment by oleg-nenashev** [comment]
CC @jenkinsci/java11-support

**Comment by oleg-nenashev** [comment]
`RCN_REDUNDANT_NULLCHECK_WOULD_HAVE_BEEN_A_NPE` is a known issue in FindBugs/Spotbugs which comes from a Java 11 bytecode. The detector is not compatible with it so far. See https://issues.jenkins-ci.org/browse/JENKINS-53720

The only way to prevent this issue now is to supress the Detector, e.g. like in https://github.com/jenkinsci/git-client-plugin/blob/7563fc7ed6a9af1cb33e8d6cd0aed9257c291de9/src/main/java/org/jenkinsci/plugins/gitclient/LegacyCompatibleGitAPIImpl.java#L175

**Comment by oleg-nenashev** [comment]
@alecharp @pavel-github Note that this PR patches won't help CI to pass, because the submitter does not have WRITE access to the repo. The master's branch is always used. But the suppression annotation patch will do the job

**Comment by pavel-github** [comment]
@oleg-nenashev @alecharp , thanks for your input and time 👍 
P.S.: I don't like workarounds and "suppressions", but it seems I have to wait for spotbug fix.

**Comment by alecharp** [comment]
thanks @oleg-nenashev for the quick fix. @pavel-d you can remove the `Jenkinsfile` changeset if you want, as it was not related.

**Comment by batmat** [comment]
@pavel-github the recommended configuration will **not** be changed to break compatibility.
When we add new things/evolve the build, we will introduce a parameter or so to handle it.

**Pull request merged**
