### PR TITLE
Fix spotbugs warning on Jenkins > 2.100

### PR DESCRIPTION
**Pull request by alecharp**
Because of https://github.com/spotbugs/spotbugs/issues/782, it is not possible to call
the getter multiple times with a if. It requires to use a local variable.

### CODE REVIEW

**Comment by adrukh** [comment]
@alecharp thanks again for helping this plugin become better!

Can you explain how does the problem in the current implementation manifest itself? What does not work as expected?

**Comment by alecharp** [comment]
> Can you explain how does the problem in the current implementation manifest itself? What does not work as expected?

I expect that nothing is broken. However, in Jenkins `2.100`, the `Launcher#getChannel` got annotated with `@CheckForNull`. Because of this, spotbugs reported 2 warnings on the master branch build. I didn't like that (as it was marked as broken after my PR), so I looked why.

This is mainly to make sure the master branch is buildable by ci.jenkins.io. I know that you rely mainly on Travis, but as we have a "common" process to build Jenkins plugins, I just wanted to make this plugin part of it.

This and the previous PR are just me trying to get in touch with the plugin as I saw a small problem and I want to see if it's a documentation issue or a plugin implementation issue. I'll fill a PR for this once I know.

**Comment by adrukh** [comment]
Much appreciated! We'll review next week and push this in.

**Comment by alecharp** [comment]
@adrukh you can reproduce the build issue with `mvn clean verify -Djenkins.version=2.164.1`. It's also in the commit status for the latest commit on `master`.

**Comment by adrukh** [comment]
@alecharp thanks again for this contribution!

**Pull request merged**
